In [1]:
from pydataset import data
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 5000)
pd.set_option('display.max_columns', 5000)
pd.set_option('display.width', 10000)
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
data(show_doc=True) #Show wta the dataset contains

dataset_id                                                                                      title
0                AirPassengers                                                Monthly Airline Passenger Numbers 1949-1960
1                      BJsales                                                          Sales Data with Leading Indicator
2                          BOD                                                                  Biochemical Oxygen Demand
3                 Formaldehyde                                                              Determination of Formaldehyde
4                 HairEyeColor                                                  Hair and Eye Color of Statistics Students
5                 InsectSprays                                                             Effectiveness of Insect Sprays
6               JohnsonJohnson                                             Quarterly Earnings per Johnson & Johnson Share
7                    LakeHuron                                                              Level of Lake Huron 1875-1972
8             LifeCycleSavings                                                       Intercountry Life-Cycle Savings Data
9                         Nile                                                                     Flow of the River Nile
10               OrchardSprays                                                                  Potency of Orchard Sprays
11                 PlantGrowth                                                 Results from an Experiment on Plant Growth
12                   Puromycin                                                 Reaction Velocity of an Enzymatic Reaction
13                     Titanic                                                      Survival of passengers on the Titanic
14                 ToothGrowth                                     The Effect of Vitamin C on Tooth Growth in Guinea Pigs
15               UCBAdmissions                                                          Student Admissions at UC Berkeley
16              UKDriverDeaths                                                   Road Casualties in Great Britain 1969-84
17                       UKgas                                                               UK Quarterly Gas Consumption
18                 USAccDeaths                                                      Accidental Deaths in the US 1973-1978
19                   USArrests                                                            Violent Crime Rates by US State
20              USJudgeRatings                                  Lawyers' Ratings of State Judges in the US Superior Court
21       USPersonalExpenditure                                                                  Personal Expenditure Data
22                    VADeaths                                                             Death Rates in Virginia (1940)
23                    WWWusage                                                                  Internet Usage per Minute
24                 WorldPhones                                                                     The World's Telephones
25                    airmiles                                       Passenger Miles on Commercial US Airlines, 1937-1960
26                  airquality                                                          New York Air Quality Measurements
27                    anscombe                                Anscombe's Quartet of 'Identical' Simple Linear Regressions
28                      attenu                                                          The Joyner-Boore Attenuation Data
29                    attitude                                                         The Chatterjee-Price Attitude Data
30                     austres                                Quarterly Time Series of the Number of Australian Residents
31                        cars                                                       Speed and Stopping Distances of

In [3]:
data('Fair')

sex   age      ym child  religious  education  occupation  rate  nbaffairs
1      male  37.0  10.000    no          3         18           7     4          0
2    female  27.0   4.000    no          4         14           6     4          0
3    female  32.0  15.000   yes          1         12           1     4          0
4      male  57.0  15.000   yes          5         18           6     5          0
5      male  22.0   0.750    no          2         17           6     3          0
6    female  32.0   1.500    no          2         17           5     5          0
7    female  22.0   0.750    no          2         12           1     3          0
8      male  57.0  15.000   yes          2         14           4     4          0
9    female  32.0  15.000   yes          4         16           1     2          0
10     male  22.0   1.500    no          4         14           4     5          0
11     male  37.0  15.000   yes          2         20           7     2          0
12     male  27.0   4.000   yes          4         18           6     4          0
13     male  47.0  15.000   yes          5         17           6     4          0
14   female  22.0   1.500    no          2         17           5     4          0
15   female  27.0   4.000    no          4         14           5     4          0
16   female  37.0  15.000   yes          1         17           5     5          0
17   female  37.0  15.000   yes          2         18           4     3          0
18   female  22.0   0.750    no          3         16           5     4          0
19   female  22.0   1.500    no          2         16           5     5          0
20   female  27.0  10.000   yes          2         14           1     5          0
21   female  22.0   1.500    no          2         16           5     5          0
22   female  22.0   1.500    no          2         16           5     5          0
23   female  27.0  10.000   yes          4         16           5     4          0
24   female  32.0  10.000   yes          3         14           1     5          0
25     male  37.0   4.000   yes          2         20           6     4          0
26   female  22.0   1.500    no          2         18           5     5          0
27   female  27.0   7.000    no          4         16           1     5          0
28     male  42.0  15.000   yes          5         20           6     4          0
29     male  27.0   4.000   yes          3         16           5     5          0
30   female  27.0   4.000   yes          3         17           5     4          0
31     male  42.0  15.000   yes          4         20           6     3          0
32   female  22.0   1.500    no          3         16           5     5          0
33     male  27.0   0.417    no          4         17           6     4          0
34   female  42.0  15.000   yes          5         14           5     4          0
35     male  32.0   4.000   yes          1         18           6     4          0
36   female  22.0   1.500    no          4         16           5     3          0
37   female  42.0  15.000   yes          3         12           1     4          0
38   female  22.0   4.000    no          4         17           5     5          0
39     male  22.0   1.500   yes          1         14           3     5          0
40   female  22.0   0.750    no          3         16           1     5          0
41     male  32.0  10.000   yes          5         20           6     5          0
42     male  52.0  15.000   yes          5         18           6     3          0
43   female  22.0   0.417    no          5         14           1     4          0
44   female  27.0   4.000   yes          2         18           6     1          0
45   female  32.0   7.000   yes          5         17           5     3          0
46     male  22.0   4.000    no          3         16           5     5          0
47   female  27.0   7.000   yes          4         18           6     5          0
48   female  42.0  15.00

In [4]:
df=pd.DataFrame(data('Fair')) #Convert the dataset to pandas dataframe

In [5]:
df.describe() #NB: describe without brackets provides all dataset

age          ym   religious   education  occupation        rate   nbaffairs
count  601.000000  601.000000  601.000000  601.000000  601.000000  601.000000  601.000000
mean    32.487521    8.177696    3.116473   16.166389    4.194676    3.931780    1.455907
std      9.288762    5.571303    1.167509    2.402555    1.819443    1.103179    3.298758
min     17.500000    0.125000    1.000000    9.000000    1.000000    1.000000    0.000000
25%     27.000000    4.000000    2.000000   14.000000    3.000000    3.000000    0.000000
50%     32.000000    7.000000    3.000000   16.000000    5.000000    4.000000    0.000000
75%     37.000000   15.000000    4.000000   18.000000    6.000000    5.000000    0.000000
max     57.000000   15.000000    5.000000   20.000000    7.000000    5.000000   12.000000

In [6]:
df.head()
df.dtypes

sex            object
age           float64
ym            float64
child          object
religious       int64
education       int64
occupation      int64
rate            int64
nbaffairs       int64
dtype: object

In [7]:
df.head()


sex   age     ym child  religious  education  occupation  rate  nbaffairs
1    male  37.0  10.00    no          3         18           7     4          0
2  female  27.0   4.00    no          4         14           6     4          0
3  female  32.0  15.00   yes          1         12           1     4          0
4    male  57.0  15.00   yes          5         18           6     5          0
5    male  22.0   0.75    no          2         17           6     3          0

### LabelEncoder to transform string to numeric

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])

In [10]:
list(le.classes_) #Male=1 Females=0

['female', 'male']

In [11]:
df.sex.dtypes

dtype('int32')

In [12]:
df['child']=le.fit_transform(df['child'])
df.head()

sex   age     ym  child  religious  education  occupation  rate  nbaffairs
1    1  37.0  10.00      0          3         18           7     4          0
2    0  27.0   4.00      0          4         14           6     4          0
3    0  32.0  15.00      1          1         12           1     4          0
4    1  57.0  15.00      1          5         18           6     5          0
5    1  22.0   0.75      0          2         17           6     3          0

In [120]:
from sklearn.model_selection import train_test_split 

We need to separate target and features first by specifying the variables

In [121]:
X=df[['religious','age','sex','ym','education','occupation','nbaffairs']] #These are the features

In [122]:
y=df['rate'] #This is the target

In [123]:
X.shape #Has 601 rows X 7 columns

(601, 7)

In [17]:
y.shape

(601,)

In [124]:
lreg=LinearRegression()

In [125]:
lreg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [126]:
lreg.coef_

array([ 0.04235281, -0.00905965, -0.08882013, -0.0304588 ,  0.06810256,
       -0.00597951, -0.07882571])

In [130]:
x=zip(X, lreg.coef_)
x=set(x)
x

{('age', -0.009059645428673794),
 ('education', 0.06810255742293699),
 ('nbaffairs', -0.07882571247653962),
 ('occupation', -0.005979506852998183),
 ('religious', 0.04235281110639181),
 ('sex', -0.08882013337087086),
 ('ym', -0.030458802565476582)}

In [134]:
elastic1=ElasticNet(normalize=True,alpha=0.001,l1_ratio=0.75)

In [135]:
elastic1.fit(X, y)

ElasticNet(alpha=0.001, copy_X=True, fit_intercept=True, l1_ratio=0.75,
      max_iter=1000, normalize=True, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [136]:
elastic1.coef_

array([ 0.01947542, -0.0086309 , -0.01811646, -0.02422483,  0.04429086,
       -0.        , -0.06679514])

In [137]:
c=zip(X, elastic1.coef_)
c=set(c)
c

{('age', -0.008630896492807707),
 ('education', 0.044290855954486306),
 ('nbaffairs', -0.06679513627963518),
 ('occupation', -0.0),
 ('religious', 0.01947541724957855),
 ('sex', -0.018116464568090695),
 ('ym', -0.024224831274512946)}

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

In [19]:
X_train.shape

(480, 7)

In [20]:
X_test.shape

(121, 7)

In [21]:
X_test.head()

religious   age  sex     ym  education  occupation  nbaffairs
524          4  22.0    1   4.00         14           2          1
69           5  22.0    0   1.50         16           5          0
430          4  32.0    1  10.00         18           5          0
214          2  27.0    1   0.75         17           5          0
240          4  37.0    0  15.00         16           4          0

In [22]:
y_train.shape

(480,)

In [23]:
y_test.shape

(121,)

In [24]:
lr=LinearRegression() #Import, Initialize, Fit, Predict

In [25]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [26]:
lr.coef_

array([ 0.08057554, -0.01198461, -0.18913541, -0.02643836,  0.07202561,
        0.00117245, -0.07300253])

In [27]:
a=zip(X, lr.coef_)
a=set(a)
a

{('age', -0.011984607686739817),
 ('education', 0.0720256077663981),
 ('nbaffairs', -0.0730025304822982),
 ('occupation', 0.0011724465475907995),
 ('religious', 0.08057553741317663),
 ('sex', -0.18913541245294802),
 ('ym', -0.026438362026868722)}

In [28]:
predicted = lr.predict(X_test)
predicted[1]

4.5538160838975035

In [29]:
b=zip(X_test, predicted)
b=set(b)
b


{('age', 4.5538160838975035),
 ('education', 3.9353810972729106),
 ('nbaffairs', 3.2038885136135358),
 ('occupation', 3.6134991435973567),
 ('religious', 3.99743814330634),
 ('sex', 4.083584195468393),
 ('ym', 4.154885400057876)}

In [30]:
X_train.head()

religious   age  sex    ym  education  occupation  nbaffairs
469          3  27.0    0   4.0         17           5          7
268          2  32.0    0  10.0         14           5          0
533          1  37.0    1   4.0         20           6          7
566          4  27.0    0  10.0         14           1          2
118          5  32.0    1  10.0         18           6          0

In [31]:
elastic=ElasticNet(normalize=True,alpha=0.001,l1_ratio=0.75) #Recommended values
elastic

ElasticNet(alpha=0.001, copy_X=True, fit_intercept=True, l1_ratio=0.75,
      max_iter=1000, normalize=True, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [32]:
elastic.fit(X_train, y_train)

ElasticNet(alpha=0.001, copy_X=True, fit_intercept=True, l1_ratio=0.75,
      max_iter=1000, normalize=True, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [33]:
elastic.coef_

array([ 0.05630305, -0.01041307, -0.10810484, -0.0226719 ,  0.04978403,
        0.        , -0.06378072])

In [34]:
# params = np.append(lm.intercept_,lm.coef_)
# predictions = lm.predict(X_)

# newX = pd.DataFrame({"Constant":np.ones(len(X))}).join(pd.DataFrame(X_train))
# MSE = (sum((y-predictions)**2))/(len(newX)-len(newX.columns))

# # Note if you don't want to use a DataFrame replace the two lines above with
# # newX = np.append(np.ones((len(X),1)), X, axis=1)
# # MSE = (sum((y-predictions)**2))/(len(newX)-len(newX[0]))

# var_b = MSE*(np.linalg.inv(np.dot(newX.T,newX)).diagonal())
# sd_b = np.sqrt(var_b)
# ts_b = params/ sd_b

# p_values =[2*(1-stats.t.cdf(np.abs(i),(len(newX)-1))) for i in ts_b]

# sd_b = np.round(sd_b,3)
# ts_b = np.round(ts_b,3)
# p_values = np.round(p_values,3)
# params = np.round(params,4)

# myDF3 = pd.DataFrame()
# myDF3["Coefficients"],myDF3["Standard Errors"],myDF3["t values"],myDF3["Probabilites"] = [params,sd_b,ts_b,p_values]
# print(myDF3)

In [35]:
b=zip(X, elastic.coef_)
b=set(b)
b

{('age', -0.010413074644719869),
 ('education', 0.049784030588360804),
 ('nbaffairs', -0.06378072195657516),
 ('occupation', 0.0),
 ('religious', 0.056303052082321045),
 ('sex', -0.108104838850348),
 ('ym', -0.022671896004194513)}

In [36]:
a=zip(X, lr.coef_)
a=set(a)
a

{('age', -0.011984607686739817),
 ('education', 0.0720256077663981),
 ('nbaffairs', -0.0730025304822982),
 ('occupation', 0.0011724465475907995),
 ('religious', 0.08057553741317663),
 ('sex', -0.18913541245294802),
 ('ym', -0.026438362026868722)}

##### KFOLD CROSSVALIDATION

In [37]:
from sklearn.model_selection import KFold

In [38]:
X.head() #Previous features and target

religious   age  sex     ym  education  occupation  nbaffairs
1          3  37.0    1  10.00         18           7          0
2          4  27.0    0   4.00         14           6          0
3          1  32.0    0  15.00         12           1          0
4          5  57.0    1  15.00         18           6          0
5          2  22.0    1   0.75         17           6          0

In [39]:
X.head()

religious   age  sex     ym  education  occupation  nbaffairs
1          3  37.0    1  10.00         18           7          0
2          4  27.0    0   4.00         14           6          0
3          1  32.0    0  15.00         12           1          0
4          5  57.0    1  15.00         18           6          0
5          2  22.0    1   0.75         17           6          0

In [40]:
kfold = KFold(3, True, 1)

In [41]:
kfold

KFold(n_splits=3, random_state=1, shuffle=True)

Normalize data with MinMaxScaler

This technique re-scales the data between a specified range(in this case, between 0–1), to ensure that certain features do not affect the final prediction more than the other features.

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [71]:
scaler = MinMaxScaler(feature_range=(0, 1))

In [72]:
X_trans = scaler.fit_transform(X)

c:\users\colli\appdata\local\programs\python\python37\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int32, int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [90]:
X_trans

array([[0.5       , 0.49367089, 1.        , ..., 0.81818182, 1.        ,
        0.        ],
       [0.75      , 0.24050633, 0.        , ..., 0.45454545, 0.83333333,
        0.        ],
       [0.        , 0.36708861, 0.        , ..., 0.27272727, 0.        ,
        0.        ],
       ...,
       [0.25      , 0.36708861, 1.        , ..., 0.72727273, 0.83333333,
        0.16666667],
       [0.5       , 0.11392405, 1.        , ..., 0.81818182, 0.83333333,
        0.16666667],
       [0.5       , 0.36708861, 0.        , ..., 0.45454545, 0.        ,
        0.08333333]])

In [91]:
y=pd.Series(y)
y

1      4
2      4
3      4
4      5
5      3
6      5
7      3
8      4
9      2
10     5
11     2
12     4
13     4
14     4
15     4
16     5
17     3
18     4
19     5
20     5
21     5
22     5
23     4
24     5
25     4
26     5
27     5
28     4
29     5
30     4
31     3
32     5
33     4
34     4
35     4
36     3
37     4
38     5
39     5
40     5
41     5
42     3
43     4
44     1
45     3
46     5
47     5
48     4
49     5
50     4
51     5
52     4
53     5
54     4
55     5
56     1
57     4
58     5
59     4
60     4
61     2
62     4
63     5
64     5
65     4
66     5
67     4
68     5
69     5
70     4
71     5
72     5
73     5
74     3
75     5
76     5
77     5
78     5
79     5
80     2
81     5
82     5
83     4
84     3
85     5
86     4
87     5
88     2
89     5
90     4
91     4
92     3
93     4
94     3
95     4
96     5
97     1
98     4
99     5
100    5
101    5
102    4
103    5
104    5
105    4
106    4
107    4
108    4
109    3
110    4
111    5
1

In [96]:
# enumerate splits     10 Splits
cv = KFold(n_splits=10, random_state=4, shuffle=False)
for trained, tested in cv.split(X_trans):
    print("Train Index: ", trained, "\n")
    print("Test Index: ", tested)

Train Index:  [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114
 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132
 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168
 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204
 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222
 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240
 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258
 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276
 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294
 295 296 297 298 299 300 301 302 303 

In [97]:
X_train, X_test, y_train, y_test = X_trans[trained], X_trans[tested], y[trained], y[tested]

In [98]:
y_train.count(), y_test.count()

(540, 60)

In [99]:
# y_test.fillna(method='ffill',inplace=True)

In [111]:
y_train.fillna(inplace=True, value=5)

In [112]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [113]:
lr.coef_

array([ 0.07899822, -0.14888505, -0.17992299,  0.23141852,  0.3114428 ,
        0.10311167, -0.61034492])

In [115]:
# k=zip(X_trans, lr.coef_)
# k=set(k)
# k

In [116]:
elastic.fit(X_train, y_train)

ElasticNet(alpha=0.001, copy_X=True, fit_intercept=True, l1_ratio=0.75,
      max_iter=1000, normalize=True, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [117]:
elastic.coef_

array([ 0.0343515 ,  0.        , -0.09388384,  0.09624051,  0.18264118,
        0.00959034, -0.45908946])